# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClassWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Function import *
import shutil
from Class import*

class Ui_ClassWin(object):
    def setupUi(self, ClassWin,searchingColor):
        ClassWin.setObjectName("ClassWin")
        ClassWin.resize(621, 777)

        self.Name = ''
        self.SearchingColor = searchingColor
        self.html = ''
        self.B_im = False
        self.B_label = False
        self.paragraph = 0
        self.done = False

        self.information2 = QtWidgets.QPushButton(ClassWin)
        self.information2.setGeometry(QtCore.QRect(350, 480, 111, 28))
        self.information2.setObjectName("information2")
        self.information3 = QtWidgets.QPushButton(ClassWin)
        self.information3.setGeometry(QtCore.QRect(350, 550, 111, 28))
        self.information3.setObjectName("information3")
        self.label = QtWidgets.QLabel(ClassWin)
        self.label.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label.setObjectName("label")
        self.Border_Wid = QtWidgets.QLineEdit(ClassWin)
        self.Border_Wid.setGeometry(QtCore.QRect(200, 580, 113, 21))
        self.Border_Wid.setObjectName("Border_Wid")
        self.ColorPaleet_2 = QtWidgets.QPushButton(ClassWin)
        self.ColorPaleet_2.setGeometry(QtCore.QRect(350, 610, 211, 28))
        self.ColorPaleet_2.setObjectName("ColorPaleet_2")
        self.ColorName = QtWidgets.QPushButton(ClassWin)
        self.ColorName.setGeometry(QtCore.QRect(110, 280, 141, 28))
        self.ColorName.setObjectName("ColorName")
        self.B_image = QtWidgets.QPushButton(ClassWin)
        self.B_image.setGeometry(QtCore.QRect(420, 240, 61, 28))
        self.B_image.setObjectName("B_image")
        self.ColorName_3 = QtWidgets.QPushButton(ClassWin)
        self.ColorName_3.setGeometry(QtCore.QRect(90, 170, 141, 28))
        self.ColorName_3.setObjectName("ColorName_3")
        self.label_16 = QtWidgets.QLabel(ClassWin)
        self.label_16.setGeometry(QtCore.QRect(60, 610, 131, 16))
        self.label_16.setObjectName("label_16")
        self.BorderRad = QtWidgets.QLineEdit(ClassWin)
        self.BorderRad.setGeometry(QtCore.QRect(200, 650, 113, 21))
        self.BorderRad.setObjectName("BorderRad")
        self.B_SearchImage = QtWidgets.QPushButton(ClassWin)
        self.B_SearchImage.setGeometry(QtCore.QRect(380, 240, 21, 28))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.B_SearchImage.setFont(font)
        self.B_SearchImage.setObjectName("B_SearchImage")
        self.information = QtWidgets.QPushButton(ClassWin)
        self.information.setGeometry(QtCore.QRect(350, 440, 111, 28))
        self.information.setObjectName("information")
        self.padding = QtWidgets.QLineEdit(ClassWin)
        self.padding.setGeometry(QtCore.QRect(200, 440, 113, 21))
        self.padding.setObjectName("padding")
        self.FontSize = QtWidgets.QLineEdit(ClassWin)
        self.FontSize.setGeometry(QtCore.QRect(150, 70, 113, 21))
        self.FontSize.setObjectName("FontSize")
        self.label_15 = QtWidgets.QLabel(ClassWin)
        self.label_15.setGeometry(QtCore.QRect(320, 580, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(ClassWin)
        self.label_17.setGeometry(QtCore.QRect(320, 440, 16, 16))
        self.label_17.setObjectName("label_17")
        self.R_Bottom = QtWidgets.QCheckBox(ClassWin)
        self.R_Bottom.setGeometry(QtCore.QRect(430, 690, 71, 19))
        self.R_Bottom.setObjectName("R_Bottom")
        self.label_7 = QtWidgets.QLabel(ClassWin)
        self.label_7.setGeometry(QtCore.QRect(50, 280, 72, 15))
        self.label_7.setObjectName("label_7")
        self.Margin = QtWidgets.QLineEdit(ClassWin)
        self.Margin.setGeometry(QtCore.QRect(200, 480, 113, 21))
        self.Margin.setObjectName("Margin")
        self.ColorPaleet_3 = QtWidgets.QPushButton(ClassWin)
        self.ColorPaleet_3.setGeometry(QtCore.QRect(240, 170, 211, 28))
        self.ColorPaleet_3.setObjectName("ColorPaleet_3")
        self.label_18 = QtWidgets.QLabel(ClassWin)
        self.label_18.setGeometry(QtCore.QRect(320, 480, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(ClassWin)
        self.label_14.setGeometry(QtCore.QRect(60, 580, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(ClassWin)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_20 = QtWidgets.QLabel(ClassWin)
        self.label_20.setGeometry(QtCore.QRect(320, 650, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_9 = QtWidgets.QLabel(ClassWin)
        self.label_9.setGeometry(QtCore.QRect(30, 440, 72, 15))
        self.label_9.setObjectName("label_9")
        self.ColorPaleet = QtWidgets.QPushButton(ClassWin)
        self.ColorPaleet.setGeometry(QtCore.QRect(260, 280, 211, 28))
        self.ColorPaleet.setObjectName("ColorPaleet")
        self.label_13 = QtWidgets.QLabel(ClassWin)
        self.label_13.setGeometry(QtCore.QRect(60, 550, 131, 16))
        self.label_13.setObjectName("label_13")
        self.RepeatX = QtWidgets.QCheckBox(ClassWin)
        self.RepeatX.setGeometry(QtCore.QRect(110, 330, 115, 19))
        self.RepeatX.setObjectName("RepeatX")
        self.label_12 = QtWidgets.QLabel(ClassWin)
        self.label_12.setGeometry(QtCore.QRect(30, 520, 72, 15))
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(ClassWin)
        self.label_10.setGeometry(QtCore.QRect(30, 480, 72, 15))
        self.label_10.setObjectName("label_10")
        self.RepeatY = QtWidgets.QCheckBox(ClassWin)
        self.RepeatY.setGeometry(QtCore.QRect(110, 360, 115, 19))
        self.RepeatY.setObjectName("RepeatY")
        self.label_2 = QtWidgets.QLabel(ClassWin)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.R_Left = QtWidgets.QCheckBox(ClassWin)
        self.R_Left.setGeometry(QtCore.QRect(180, 690, 71, 19))
        self.R_Left.setObjectName("R_Left")
        self.R_Right = QtWidgets.QCheckBox(ClassWin)
        self.R_Right.setGeometry(QtCore.QRect(310, 690, 71, 19))
        self.R_Right.setObjectName("R_Right")
        self.label_3 = QtWidgets.QLabel(ClassWin)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 351, 16))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(ClassWin)
        self.label_8.setGeometry(QtCore.QRect(30, 400, 141, 16))
        self.label_8.setObjectName("label_8")
        self.label_24 = QtWidgets.QLabel(ClassWin)
        self.label_24.setGeometry(QtCore.QRect(30, 170, 72, 15))
        self.label_24.setObjectName("label_24")
        self.Font = QtWidgets.QComboBox(ClassWin)
        self.Font.setGeometry(QtCore.QRect(150, 100, 231, 22))
        self.Font.setObjectName("Font")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.label_4 = QtWidgets.QLabel(ClassWin)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 111, 16))
        self.label_4.setObjectName("label_4")
        self.C_BorderStyle = QtWidgets.QComboBox(ClassWin)
        self.C_BorderStyle.setGeometry(QtCore.QRect(200, 550, 111, 22))
        self.C_BorderStyle.setObjectName("C_BorderStyle")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_Align = QtWidgets.QComboBox(ClassWin)
        self.C_Align.setGeometry(QtCore.QRect(200, 400, 121, 22))
        self.C_Align.setObjectName("C_Align")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.label_6 = QtWidgets.QLabel(ClassWin)
        self.label_6.setGeometry(QtCore.QRect(110, 240, 191, 16))
        self.label_6.setObjectName("label_6")
        self.R_Top = QtWidgets.QCheckBox(ClassWin)
        self.R_Top.setGeometry(QtCore.QRect(60, 690, 71, 19))
        self.R_Top.setObjectName("R_Top")
        self.ColorName_2 = QtWidgets.QPushButton(ClassWin)
        self.ColorName_2.setGeometry(QtCore.QRect(200, 610, 141, 28))
        self.ColorName_2.setObjectName("ColorName_2")
        self.label_19 = QtWidgets.QLabel(ClassWin)
        self.label_19.setGeometry(QtCore.QRect(60, 650, 121, 16))
        self.label_19.setObjectName("label_19")
        self.Finish = QtWidgets.QPushButton(ClassWin)
        self.Finish.setGeometry(QtCore.QRect(510, 730, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Cancel = QtWidgets.QPushButton(ClassWin)
        self.Cancel.setGeometry(QtCore.QRect(400, 730, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.label_11 = QtWidgets.QLabel(ClassWin)
        self.label_11.setGeometry(QtCore.QRect(290, 70, 72, 15))
        self.label_11.setObjectName("label_11")
        self.label_21 = QtWidgets.QLabel(ClassWin)
        self.label_21.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label_21.setObjectName("label_21")
        self.Name = QtWidgets.QLineEdit(ClassWin)
        self.Name.setGeometry(QtCore.QRect(150, 30, 113, 21))
        self.Name.setObjectName("Name")
        ##############################
        self.color = Color()
        self.color.name = ""
        self.color.html = "#ffffff"
        self.B_Background = MyInt(-1)
        self.background = Color()
        self.BorderColor = Color()
        self.BorderColor.html = "#ffffff"
        self.BorderColor.name = ""
        ############################
        self.retranslateUi(ClassWin)
        QtCore.QMetaObject.connectSlotsByName(ClassWin)

    def retranslateUi(self, ClassWin):
        _translate = QtCore.QCoreApplication.translate
        ClassWin.setWindowTitle(_translate("ClassWin", "Class Window"))
        self.information2.setText(_translate("ClassWin", "information"))
        self.information3.setText(_translate("ClassWin", "information"))
        self.label.setText(_translate("ClassWin", "Font Size:"))
        self.Border_Wid.setText(_translate("ClassWin", "0"))
        self.ColorPaleet_2.setText(_translate("ClassWin", "choose by Colour Paleet"))
        self.ColorName.setText(_translate("ClassWin", "choose by name"))
        self.B_image.setText(_translate("ClassWin", "apply"))
        self.ColorName_3.setText(_translate("ClassWin", "choose by name"))
        self.label_16.setText(_translate("ClassWin", "Border Color:"))
        self.BorderRad.setText(_translate("ClassWin", "0"))
        self.B_SearchImage.setText(_translate("ClassWin", "⋮"))
        self.information.setText(_translate("ClassWin", "information"))
        self.padding.setText(_translate("ClassWin", "default"))
        self.FontSize.setText(_translate("ClassWin", "default"))
        self.label_15.setText(_translate("ClassWin", "px"))
        self.label_17.setText(_translate("ClassWin", "px"))
        self.R_Bottom.setText(_translate("ClassWin", "Bottom"))
        self.label_7.setText(_translate("ClassWin", "Color:"))
        self.Margin.setText(_translate("ClassWin", "default"))
        self.ColorPaleet_3.setText(_translate("ClassWin", "choose by Colour Paleet"))
        self.label_18.setText(_translate("ClassWin", "px"))
        self.label_14.setText(_translate("ClassWin", "Border Width:"))
        self.label_5.setText(_translate("ClassWin", "image:"))
        self.label_20.setText(_translate("ClassWin", "px"))
        self.label_9.setText(_translate("ClassWin", "Padding:"))
        self.ColorPaleet.setText(_translate("ClassWin", "choose by Colour Paleet"))
        self.label_13.setText(_translate("ClassWin", "Border Style:"))
        self.RepeatX.setText(_translate("ClassWin", "Repeat x"))
        self.label_12.setText(_translate("ClassWin", "Border:"))
        self.label_10.setText(_translate("ClassWin", "Margin:"))
        self.RepeatY.setText(_translate("ClassWin", "Repeat y"))
        self.label_2.setText(_translate("ClassWin", "Font:"))
        self.R_Left.setText(_translate("ClassWin", "Left"))
        self.R_Right.setText(_translate("ClassWin", "Right"))
        self.label_3.setText(_translate("ClassWin", "0123456789abcdefghijklmnopgrstuvwxyz"))
        self.label_8.setText(_translate("ClassWin", "Text Alignment:"))
        self.label_24.setText(_translate("ClassWin", "Color:"))
        self.Font.setItemText(0, _translate("ClassWin", "Arial (sans-serif)"))
        self.Font.setItemText(1, _translate("ClassWin", "Verdana (sans-serif)"))
        self.Font.setItemText(2, _translate("ClassWin", "Helvetica (sans-serif)\n"
""))
        self.Font.setItemText(3, _translate("ClassWin", "Tahoma (sans-serif)"))
        self.Font.setItemText(4, _translate("ClassWin", "Trebuchet MS (sans-serif)"))
        self.Font.setItemText(5, _translate("ClassWin", "Times New Roman (serif)"))
        self.Font.setItemText(6, _translate("ClassWin", "Georgia (serif)"))
        self.Font.setItemText(7, _translate("ClassWin", "Garamond (serif)"))
        self.Font.setItemText(8, _translate("ClassWin", "Courier New (monospace)"))
        self.Font.setItemText(9, _translate("ClassWin", "Brush Script MT (cursive)"))
        self.label_4.setText(_translate("ClassWin", "background:"))
        self.C_BorderStyle.setItemText(0, _translate("ClassWin", "none"))
        self.C_BorderStyle.setItemText(1, _translate("ClassWin", "dotted"))
        self.C_BorderStyle.setItemText(2, _translate("ClassWin", "dashed"))
        self.C_BorderStyle.setItemText(3, _translate("ClassWin", "solid"))
        self.C_BorderStyle.setItemText(4, _translate("ClassWin", "double"))
        self.C_BorderStyle.setItemText(5, _translate("ClassWin", "groove"))
        self.C_BorderStyle.setItemText(6, _translate("ClassWin", "ridge"))
        self.C_BorderStyle.setItemText(7, _translate("ClassWin", "inset"))
        self.C_BorderStyle.setItemText(8, _translate("ClassWin", "outset"))
        self.C_BorderStyle.setItemText(9, _translate("ClassWin", "hidden"))
        self.C_Align.setItemText(0, _translate("ClassWin", "justify"))
        self.C_Align.setItemText(1, _translate("ClassWin", "right"))
        self.C_Align.setItemText(2, _translate("ClassWin", "left"))
        self.C_Align.setItemText(3, _translate("ClassWin", "center"))
        self.label_6.setText(_translate("ClassWin", "imageName"))
        self.R_Top.setText(_translate("ClassWin", "Top"))
        self.ColorName_2.setText(_translate("ClassWin", "choose by name"))
        self.label_19.setText(_translate("ClassWin", "Border Radius:"))
        self.Finish.setText(_translate("ClassWin", "Finish"))
        self.Cancel.setText(_translate("ClassWin", "Cancel"))
        self.label_11.setText(_translate("ClassWin", "px"))
        self.label_21.setText(_translate("ClassWin", "Name:"))
        #############################################
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.Font.currentIndexChanged.connect(self.FontChanged)
        self.ColorPaleet.clicked.connect(lambda state, x=self.background,y=self.B_Background: self.ClickColor1(x,y))
        self.ColorName.clicked.connect(lambda state, x=self.background,y=self.B_Background: self.ChooseColorByName1(x,y))
        self.ColorPaleet_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ClickColor1(x,y))
        self.ColorName_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ChooseColorByName1(x,y))
        self.ColorPaleet_3.clicked.connect(lambda state, x=self.color,y="default": self.ClickColor1(x,y))
        self.ColorName_3.clicked.connect(lambda state, x=self.color,y="default": self.ChooseColorByName1(x,y))
        self.information.clicked.connect(lambda state, x="The CSS padding properties are used to generate space around an element's content, inside of any defined borders. it is editted as padding:PADDING WIDTH px inside Style.":Information(x))
        self.information2.clicked.connect(lambda state, x="The CSS margin properties are used to create space around elements, outside of any defined borders. it is editted as margin:MARGIN WIDTH px inside Style.":Information(x))
        self.information3.clicked.connect(lambda state,x="Borders style,Border Width,Border color,border radius can be edited as border-style:BORDER STYLE;border-width:WIDTH px;border-radius:RADIUS px; border style is set for rounded borders":Information(x))

    def ChooseColorByName1(self,changed,boolean):
        New=self.GetColor()
        if(New):

            if(boolean!="default"):
                boolean.int = 1
                changed.html=New.html
                changed.name=New.name
            else:
                changed.html=New.html
                changed.name=New.name

    def GetColor(self):
        New = Color()
        self.SearchingColor.Repersent(New)
        if (New.name != ''):

            return New
        else:
            return False
    def ClickColor1(self,changed,boolea):

        New=openColorDialog()

        if (New):
            if (boolea !="default"):

                boolea.int = 1
                changed.name = New.name
                changed.html=New.html
            else:
                changed.name = New.name
                changed.html = New.html
                print(changed.html)

    def clear(self):
        _translate = QtCore.QCoreApplication.translate
        self.html = ''
        self.B_im = False
        self.B_label = False
        self.paragraph = 0
        self.done = False
        self.color.name=""
        self.color.html="#ffffff"
        self.B_Background.int=-1
        self.background.html=""
        self.background.name=""
        self.BorderColor.html="#ffffff"
        self.BorderColor.name=""
        self.Margin.setText("default")
        self.Font.setCurrentIndex(0)
        self.label_3.setText(_translate("ParagraphWin", "0123456789abcdefghijklmnopgrstuvwxyz"))
        self.BorderRad.setText(_translate("ParagraphWin", "0"))
        self.Border_Wid.setText(_translate("ParagraphWin", "0"))
        self.padding.setText(_translate("ParagraphWin", "default"))
        self.FontSize.setText(_translate("ParagraphWin", "default"))
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.RepeatX.setChecked(False)
        self.RepeatY.setChecked(False)

    def FontChanged(self,int):
        self.label_3.setFont(QtGui.QFont(self.Font.currentText().split(" (")[0]))


