# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HeadingInfoWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Function import *
import shutil
from Class import*

class Ui_HeadingInfo(object):
    def setupUi(self, Ui_HeadingInfo,searchingColor):
        self.SearchingColor = searchingColor
        self.html = ''
        self.list = []
        self.len = 0
        self.textlist = []
        self.B_im = False
        self.B_label = False
        self.paragraph = 0
        self.done = False
        self.name=''
        Ui_HeadingInfo.setObjectName("Ui_HeadingInfo")
        Ui_HeadingInfo.resize(627, 956)
        self.label_45 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_45.setGeometry(QtCore.QRect(60, 660, 121, 16))
        self.label_45.setObjectName("label_45")
        self.label_42 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_42.setGeometry(QtCore.QRect(110, 250, 191, 16))
        self.label_42.setObjectName("label_42")
        self.Sub = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Sub.setGeometry(QtCore.QRect(260, 750, 41, 31))
        self.Sub.setObjectName("Sub")
        self.C_HeightWidthU_2 = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.C_HeightWidthU_2.setGeometry(QtCore.QRect(400, 160, 87, 22))
        self.C_HeightWidthU_2.setObjectName("C_HeightWidthU_2")
        self.C_HeightWidthU_2.addItem("")
        self.C_HeightWidthU_2.addItem("")
        self.C_HeightWidthU_2.addItem("")
        self.R_Left = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.R_Left.setGeometry(QtCore.QRect(180, 700, 71, 19))
        self.R_Left.setObjectName("R_Left")
        self.label_40 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_40.setGeometry(QtCore.QRect(170, 160, 72, 16))
        self.label_40.setObjectName("label_40")
        self.label_23 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_23.setGeometry(QtCore.QRect(30, 530, 72, 15))
        self.label_23.setObjectName("label_23")
        self.R_Top = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.R_Top.setGeometry(QtCore.QRect(60, 700, 71, 19))
        self.R_Top.setObjectName("R_Top")
        self.Width = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.Width.setGeometry(QtCore.QRect(270, 190, 113, 21))
        self.Width.setObjectName("Width")
        self.label_30 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_30.setGeometry(QtCore.QRect(30, 490, 72, 15))
        self.label_30.setObjectName("label_30")
        self.R_Right = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.R_Right.setGeometry(QtCore.QRect(310, 700, 71, 19))
        self.R_Right.setObjectName("R_Right")
        self.Italic = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Italic.setGeometry(QtCore.QRect(80, 750, 61, 31))
        self.Italic.setObjectName("Italic")
        self.Border_Wid = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.Border_Wid.setGeometry(QtCore.QRect(200, 590, 113, 21))
        self.Border_Wid.setObjectName("Border_Wid")
        self.information = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.information.setGeometry(QtCore.QRect(350, 450, 111, 28))
        self.information.setObjectName("information")
        self.information4 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.information4.setGeometry(QtCore.QRect(450, 750, 121, 31))
        self.information4.setObjectName("information4")
        self.Sup = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Sup.setGeometry(QtCore.QRect(300, 750, 41, 31))
        self.Sup.setObjectName("Sup")
        self.label_33 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_33.setGeometry(QtCore.QRect(320, 490, 16, 16))
        self.label_33.setObjectName("label_33")
        self.C_Font = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.C_Font.setGeometry(QtCore.QRect(150, 40, 231, 22))
        self.C_Font.setObjectName("C_Font")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.C_Font.addItem("")
        self.label_36 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_36.setGeometry(QtCore.QRect(30, 40, 72, 15))
        self.label_36.setObjectName("label_36")
        self.label_22 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_22.setGeometry(QtCore.QRect(60, 590, 131, 16))
        self.label_22.setObjectName("label_22")
        self.label_41 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_41.setGeometry(QtCore.QRect(30, 160, 121, 16))
        self.label_41.setObjectName("label_41")
        self.Cancel = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Cancel.setGeometry(QtCore.QRect(360, 910, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.ColorName_2 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorName_2.setGeometry(QtCore.QRect(200, 620, 141, 28))
        self.ColorName_2.setObjectName("ColorName_2")
        self.C_BorderStyle = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.C_BorderStyle.setGeometry(QtCore.QRect(200, 560, 111, 22))
        self.C_BorderStyle.setObjectName("C_BorderStyle")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.label_35 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_35.setGeometry(QtCore.QRect(30, 220, 111, 16))
        self.label_35.setObjectName("label_35")
        self.ColorPaleet_2 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorPaleet_2.setGeometry(QtCore.QRect(350, 620, 211, 28))
        self.ColorPaleet_2.setObjectName("ColorPaleet_2")
        self.information3 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.information3.setGeometry(QtCore.QRect(350, 560, 111, 28))
        self.information3.setObjectName("information3")
        self.label_29 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_29.setGeometry(QtCore.QRect(30, 80, 351, 16))
        self.label_29.setObjectName("label_29")
        self.label_26 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_26.setGeometry(QtCore.QRect(30, 450, 72, 15))
        self.label_26.setObjectName("label_26")
        self.ColorPaleet_1 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorPaleet_1.setGeometry(QtCore.QRect(260, 290, 211, 28))
        self.ColorPaleet_1.setObjectName("ColorPaleet_1")
        self.label_38 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_38.setGeometry(QtCore.QRect(170, 190, 72, 16))
        self.label_38.setObjectName("label_38")
        self.Delete = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Delete.setGeometry(QtCore.QRect(340, 750, 41, 31))
        self.Delete.setObjectName("Delete")
        self.label_31 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_31.setGeometry(QtCore.QRect(30, 730, 72, 15))
        self.label_31.setObjectName("label_31")
        self.information5 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.information5.setGeometry(QtCore.QRect(500, 160, 101, 51))
        self.information5.setObjectName("information5")
        self.information2 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.information2.setGeometry(QtCore.QRect(350, 490, 111, 28))
        self.information2.setObjectName("information2")
        self.C_Align = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.C_Align.setGeometry(QtCore.QRect(200, 410, 121, 22))
        self.C_Align.setObjectName("C_Align")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.BorderRad = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.BorderRad.setGeometry(QtCore.QRect(200, 660, 113, 21))
        self.BorderRad.setObjectName("BorderRad")
        self.B_image = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.B_image.setGeometry(QtCore.QRect(420, 250, 61, 28))
        self.B_image.setObjectName("B_image")
        self.Size = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.Size.setGeometry(QtCore.QRect(150, 10, 87, 22))
        self.Size.setObjectName("Size")
        self.Size.addItem("")
        self.Size.addItem("")
        self.Size.addItem("")
        self.Size.addItem("")
        self.Size.addItem("")
        self.Size.addItem("")
        self.ColorName_1 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorName_1.setGeometry(QtCore.QRect(110, 290, 141, 28))
        self.ColorName_1.setObjectName("ColorName_1")
        self.Margin = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.Margin.setGeometry(QtCore.QRect(200, 490, 113, 21))
        self.Margin.setObjectName("Margin")
        self.Mark = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Mark.setGeometry(QtCore.QRect(140, 750, 61, 31))
        self.Mark.setObjectName("Mark")
        self.RepeatY = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.RepeatY.setGeometry(QtCore.QRect(110, 370, 115, 19))
        self.RepeatY.setObjectName("RepeatY")
        self.label_28 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_28.setGeometry(QtCore.QRect(30, 410, 141, 16))
        self.label_28.setObjectName("label_28")
        self.Small = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Small.setGeometry(QtCore.QRect(200, 750, 61, 31))
        self.Small.setObjectName("Small")
        self.label_39 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_39.setGeometry(QtCore.QRect(320, 660, 16, 16))
        self.label_39.setObjectName("label_39")
        self.label_43 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_43.setGeometry(QtCore.QRect(50, 290, 72, 15))
        self.label_43.setObjectName("label_43")
        self.label_34 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_34.setGeometry(QtCore.QRect(50, 250, 72, 15))
        self.label_34.setObjectName("label_34")
        self.label_27 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_27.setGeometry(QtCore.QRect(60, 620, 131, 16))
        self.label_27.setObjectName("label_27")
        self.label_37 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_37.setGeometry(QtCore.QRect(320, 590, 16, 16))
        self.label_37.setObjectName("label_37")
        self.B_SearchImage = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.B_SearchImage.setGeometry(QtCore.QRect(380, 250, 21, 28))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.B_SearchImage.setFont(font)
        self.B_SearchImage.setObjectName("B_SearchImage")
        self.Bold = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Bold.setGeometry(QtCore.QRect(30, 750, 51, 31))
        self.Bold.setObjectName("Bold")
        self.Text = QtWidgets.QTextEdit(Ui_HeadingInfo)
        self.Text.setGeometry(QtCore.QRect(30, 780, 541, 111))
        self.Text.setObjectName("Text")
        self.label_44 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_44.setGeometry(QtCore.QRect(320, 450, 16, 16))
        self.label_44.setObjectName("label_44")
        self.C_HeightWidthU_1 = QtWidgets.QComboBox(Ui_HeadingInfo)
        self.C_HeightWidthU_1.setGeometry(QtCore.QRect(400, 190, 87, 22))
        self.C_HeightWidthU_1.setObjectName("C_HeightWidthU_1")
        self.C_HeightWidthU_1.addItem("")
        self.C_HeightWidthU_1.addItem("")
        self.C_HeightWidthU_1.addItem("")
        self.Height = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.Height.setGeometry(QtCore.QRect(270, 160, 113, 21))
        self.Height.setObjectName("Height")
        self.RepeatX = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.RepeatX.setGeometry(QtCore.QRect(110, 340, 115, 19))
        self.RepeatX.setObjectName("RepeatX")
        self.label_32 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_32.setGeometry(QtCore.QRect(60, 560, 131, 16))
        self.label_32.setObjectName("label_32")
        self.R_Bottom = QtWidgets.QCheckBox(Ui_HeadingInfo)
        self.R_Bottom.setGeometry(QtCore.QRect(430, 700, 71, 19))
        self.R_Bottom.setObjectName("R_Bottom")
        self.padding_2 = QtWidgets.QLineEdit(Ui_HeadingInfo)
        self.padding_2.setGeometry(QtCore.QRect(200, 450, 113, 21))
        self.padding_2.setObjectName("padding_2")
        self.Finish = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.Finish.setGeometry(QtCore.QRect(470, 910, 93, 28))
        self.Finish.setObjectName("Finish")
        self.label_24 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_24.setGeometry(QtCore.QRect(30, 10, 72, 15))
        self.label_24.setObjectName("label_24")
        self.label_46 = QtWidgets.QLabel(Ui_HeadingInfo)
        self.label_46.setGeometry(QtCore.QRect(30, 110, 72, 15))
        self.label_46.setObjectName("label_46")
        self.ColorPaleet_3 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorPaleet_3.setGeometry(QtCore.QRect(250, 110, 211, 28))
        self.ColorPaleet_3.setObjectName("ColorPaleet_3")
        self.ColorName_3 = QtWidgets.QPushButton(Ui_HeadingInfo)
        self.ColorName_3.setGeometry(QtCore.QRect(100, 110, 141, 28))
        self.ColorName_3.setObjectName("ColorName_3")
        
        self.color = Color()
        self.color.name = ""
        self.color.html = "#ffffff"
        self.B_Background = MyInt(-1)
        self.background = Color()
        self.backgroundImage=""
        self.BorderColor = Color()
        self.BorderColor.html = "#ffffff"
        self.BorderColor.name = ""
        self.label_29.setFont(QtGui.QFont(self.C_Font.currentText().split(" (")[0]))

        self.retranslateUi(Ui_HeadingInfo)
        QtCore.QMetaObject.connectSlotsByName(Ui_HeadingInfo)
        ###############################################

        self.Bold.setCheckable(True)
        self.Italic.setCheckable(True)
        self.Sub.setCheckable(True)
        self.Sup.setCheckable(True)
        self.Small.setCheckable(True)
        self.Delete.setCheckable(True)
        self.Mark.setCheckable(True)

    def retranslateUi(self, Ui_HeadingInfo):
        _translate = QtCore.QCoreApplication.translate
        Ui_HeadingInfo.setWindowTitle(_translate("Ui_HeadingInfo", "Heading information Window"))
        self.label_45.setText(_translate("Ui_HeadingInfo", "Border Radius:"))
        self.label_42.setText(_translate("Ui_HeadingInfo", "imageName"))
        self.Sub.setText(_translate("Ui_HeadingInfo", "Sub"))
        self.C_HeightWidthU_2.setItemText(0, _translate("Ui_HeadingInfo", "px"))
        self.C_HeightWidthU_2.setItemText(1, _translate("Ui_HeadingInfo", "%"))
        self.C_HeightWidthU_2.setItemText(2, _translate("Ui_HeadingInfo", "em"))
        self.R_Left.setText(_translate("Ui_HeadingInfo", "Left"))
        self.label_40.setText(_translate("Ui_HeadingInfo", "Height:"))
        self.label_23.setText(_translate("Ui_HeadingInfo", "Border:"))
        self.R_Top.setText(_translate("Ui_HeadingInfo", "Top"))
        self.Width.setText(_translate("Ui_HeadingInfo", "default"))
        self.label_30.setText(_translate("Ui_HeadingInfo", "Margin:"))
        self.R_Right.setText(_translate("Ui_HeadingInfo", "Right"))
        self.Italic.setText(_translate("Ui_HeadingInfo", "Italic"))
        self.Border_Wid.setText(_translate("Ui_HeadingInfo", "0"))
        self.information.setText(_translate("Ui_HeadingInfo", "information"))
        self.information4.setText(_translate("Ui_HeadingInfo", "information"))
        self.Sup.setText(_translate("Ui_HeadingInfo", "Sup"))
        self.label_33.setText(_translate("Ui_HeadingInfo", "px"))
        self.C_Font.setItemText(0, _translate("Ui_HeadingInfo", "Arial (sans-serif)"))
        self.C_Font.setItemText(1, _translate("Ui_HeadingInfo", "Verdana (sans-serif)"))
        self.C_Font.setItemText(2, _translate("Ui_HeadingInfo", "Helvetica (sans-serif)"))
        self.C_Font.setItemText(3, _translate("Ui_HeadingInfo", "Tahoma (sans-serif)"))
        self.C_Font.setItemText(4, _translate("Ui_HeadingInfo", "Trebuchet MS (sans-serif)"))
        self.C_Font.setItemText(5, _translate("Ui_HeadingInfo", "Times New Roman (serif)"))
        self.C_Font.setItemText(6, _translate("Ui_HeadingInfo", "Georgia (serif)"))
        self.C_Font.setItemText(7, _translate("Ui_HeadingInfo", "Garamond (serif)"))
        self.C_Font.setItemText(8, _translate("Ui_HeadingInfo", "Courier New (monospace)"))
        self.C_Font.setItemText(9, _translate("Ui_HeadingInfo", "Brush Script MT (cursive)"))
        self.label_36.setText(_translate("Ui_HeadingInfo", "Font:"))
        self.label_22.setText(_translate("Ui_HeadingInfo", "Border Width:"))
        self.label_41.setText(_translate("Ui_HeadingInfo", "Height/width:"))
        self.Cancel.setText(_translate("Ui_HeadingInfo", "Cancel"))
        self.ColorName_2.setText(_translate("Ui_HeadingInfo", "choose by name"))
        self.C_BorderStyle.setItemText(0, _translate("Ui_HeadingInfo", "none"))
        self.C_BorderStyle.setItemText(1, _translate("Ui_HeadingInfo", "dotted"))
        self.C_BorderStyle.setItemText(2, _translate("Ui_HeadingInfo", "dashed"))
        self.C_BorderStyle.setItemText(3, _translate("Ui_HeadingInfo", "solid"))
        self.C_BorderStyle.setItemText(4, _translate("Ui_HeadingInfo", "double"))
        self.C_BorderStyle.setItemText(5, _translate("Ui_HeadingInfo", "groove"))
        self.C_BorderStyle.setItemText(6, _translate("Ui_HeadingInfo", "ridge"))
        self.C_BorderStyle.setItemText(7, _translate("Ui_HeadingInfo", "inset"))
        self.C_BorderStyle.setItemText(8, _translate("Ui_HeadingInfo", "outset"))
        self.C_BorderStyle.setItemText(9, _translate("Ui_HeadingInfo", "hidden"))
        self.label_35.setText(_translate("Ui_HeadingInfo", "background:"))
        self.ColorPaleet_2.setText(_translate("Ui_HeadingInfo", "choose by Colour Paleet"))
        self.information3.setText(_translate("Ui_HeadingInfo", "information"))
        self.label_29.setText(_translate("Ui_HeadingInfo", "0123456789abcdefghijklmnopgrstuvwxyz"))
        self.label_26.setText(_translate("Ui_HeadingInfo", "Padding:"))
        self.ColorPaleet_1.setText(_translate("Ui_HeadingInfo", "choose by Colour Paleet"))
        self.label_38.setText(_translate("Ui_HeadingInfo", "Width:"))
        self.Delete.setText(_translate("Ui_HeadingInfo", "del"))
        self.label_31.setText(_translate("Ui_HeadingInfo", "Text:"))
        self.information5.setText(_translate("Ui_HeadingInfo", "information"))
        self.information2.setText(_translate("Ui_HeadingInfo", "information"))
        self.C_Align.setItemText(0, _translate("Ui_HeadingInfo", "justify"))
        self.C_Align.setItemText(1, _translate("Ui_HeadingInfo", "right"))
        self.C_Align.setItemText(2, _translate("Ui_HeadingInfo", "left"))
        self.C_Align.setItemText(3, _translate("Ui_HeadingInfo", "center"))
        self.BorderRad.setText(_translate("Ui_HeadingInfo", "0"))
        self.B_image.setText(_translate("Ui_HeadingInfo", "apply"))
        self.Size.setItemText(0, _translate("Ui_HeadingInfo", "h1"))
        self.Size.setItemText(1, _translate("Ui_HeadingInfo", "h2"))
        self.Size.setItemText(2, _translate("Ui_HeadingInfo", "h3"))
        self.Size.setItemText(3, _translate("Ui_HeadingInfo", "h4"))
        self.Size.setItemText(4, _translate("Ui_HeadingInfo", "h5"))
        self.Size.setItemText(5, _translate("Ui_HeadingInfo", "h6"))
        self.ColorName_1.setText(_translate("Ui_HeadingInfo", "choose by name"))
        self.Margin.setText(_translate("Ui_HeadingInfo", "default"))
        self.Mark.setText(_translate("Ui_HeadingInfo", "Marked"))
        self.RepeatY.setText(_translate("Ui_HeadingInfo", "Repeat y"))
        self.label_28.setText(_translate("Ui_HeadingInfo", "Text Alignment:"))
        self.Small.setText(_translate("Ui_HeadingInfo", "Small"))
        self.label_39.setText(_translate("Ui_HeadingInfo", "px"))
        self.label_43.setText(_translate("Ui_HeadingInfo", "Color:"))
        self.label_34.setText(_translate("Ui_HeadingInfo", "image:"))
        self.label_27.setText(_translate("Ui_HeadingInfo", "Border Color:"))
        self.label_37.setText(_translate("Ui_HeadingInfo", "px"))
        self.B_SearchImage.setText(_translate("Ui_HeadingInfo", "⋮"))
        self.Bold.setText(_translate("Ui_HeadingInfo", "Bold"))
        self.label_44.setText(_translate("Ui_HeadingInfo", "px"))
        self.C_HeightWidthU_1.setItemText(0, _translate("Ui_HeadingInfo", "px"))
        self.C_HeightWidthU_1.setItemText(1, _translate("Ui_HeadingInfo", "%"))
        self.C_HeightWidthU_1.setItemText(2, _translate("Ui_HeadingInfo", "em"))
        self.Height.setText(_translate("Ui_HeadingInfo", "default"))
        self.RepeatX.setText(_translate("Ui_HeadingInfo", "Repeat x"))
        self.label_32.setText(_translate("Ui_HeadingInfo", "Border Style:"))
        self.R_Bottom.setText(_translate("Ui_HeadingInfo", "Bottom"))
        self.padding_2.setText(_translate("Ui_HeadingInfo", "default"))
        self.Finish.setText(_translate("Ui_HeadingInfo", "Finish"))
        self.label_24.setText(_translate("Ui_HeadingInfo", "Size:"))
        self.label_46.setText(_translate("Ui_HeadingInfo", "Color:"))
        self.ColorPaleet_3.setText(_translate("Ui_HeadingInfo", "choose by Colour Paleet"))
        self.ColorName_3.setText(_translate("Ui_HeadingInfo", "choose by name"))
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.Text.setText("")
        self.Text.textChanged.connect(self.textWrite)
        self.Text.cursorPositionChanged.connect(self.CursorChanged)
        self.B_image.clicked.connect(self.ImageApply)
        self.Bold.clicked.connect(self.Press)
        self.Italic.clicked.connect(self.Press)
        self.Small.clicked.connect(self.Press)
        self.Sub.clicked.connect(self.Press)
        self.Sup.clicked.connect(self.Press)
        self.Delete.clicked.connect(self.Press)
        self.Mark.clicked.connect(self.Press)
        self.B_SearchImage.clicked.connect(self.seach_image)
        #self.ColorPaleet_1.clicked.connect(lambda state, x=self.background, y=self.B_Background: self.ClickColor1(x,y))
        self.ColorPaleet_1.clicked.connect(lambda state, x=self.background,y=self.B_Background:self.ClickColor1(x,y))
        self.ColorName_1.clicked.connect(lambda state, x=self.background,y=self.B_Background:self.ChooseColorByName1(x,y))
        self.ColorPaleet_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ClickColor1(x,y))
        self.ColorName_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ChooseColorByName1(x,y))
        self.ColorPaleet_3.clicked.connect(lambda state, x=self.color,y="default": self.ClickColor1(x,y))
        self.ColorName_3.clicked.connect(lambda state, x=self.color,y="default": self.ChooseColorByName1(x,y))
        self.information.clicked.connect(lambda state,
                                                x="The CSS padding properties are used to generate space around an element's content, inside of any defined borders. it is editted as padding:PADDING WIDTH px inside Style.": Information(
            x))
        self.information2.clicked.connect(lambda state,
                                                 x="The CSS margin properties are used to create space around elements, outside of any defined borders. it is editted as margin:MARGIN WIDTH px inside Style.": Information(
            x))
        self.information3.clicked.connect(lambda state,
                                                 x="Borders style,Border Width,Border color,border radius can be edited as border-style:BORDER STYLE;border-width:WIDTH px;border-radius:RADIUS px; border style is set for rounded borders": Information(
            x))
        self.information4.clicked.connect(lambda state,
                                                 x="HTML contains several elements for defining text with a special meaning.\n<b> - Bold text\n<strong> - Important text\n<i> - Italic text\n<em> - Emphasized text\n<mark> - Marked text\n<small> - Smaller text\n<del> - Deleted text\n<ins> - Inserted text\n<sub> - Subscript text\n<sup> - Superscript text\n strong bold have the same functions, and italic and em are of the same functions as well ": Information(
            x))
        self.information5.clicked.connect(lambda state,
                                                 x="for size which is not enough to repersent texts, in html it can show the whole texts out as well, but in pyqt5 it can just show the part of texts which is limited by width and height": Information(
            x))

    def FontChanged(self,int):
        self.label_29.setFont(QtGui.QFont(self.C_Font.currentText().split(" (")[0]))
    def seach_image(self):
        file=searching(IMAGEINDEX,self.name)
        if file!="":
            self.label_42.setText(file.split("/")[-1])
            self.B_im=True
            self.backgroundImage=file
    def ImageApply(self):
        if (self.B_im):
            self.B_Background.int=0
        else:
            Warning("The image file have not be set yet.")
    def ChooseColorByName1(self,changed,boolean):
        New=self.GetColor()
        if(New):

            if(boolean!="default"):
                boolean.int = 1
                changed.html=New.html
                changed.name=New.name
            else:
                changed.html=New.html
                changed.name=New.name





    def GetColor(self):
        New = Color()
        self.SearchingColor.Repersent(New)
        if (New.name != ''):

            return New
        else:
            return False

    #def ChooseColByName(self):




    def CursorChanged(self):
        cursor=self.Text.textCursor()##delete the selection of text
        if len(cursor.selectedText())>1:
            cursor.clearSelection()
            self.Text.setTextCursor(cursor)
            self.Text.setFocus()
    def Press(self):

        self.Text.setFocus()
    def ClickColor1(self,changed,boolea):

        New=openColorDialog()
        if (New):
            if (boolea !="default"):

                boolea.int = 1
                changed.name = New.name
                changed.html=New.html
            else:
                changed.name = New.name
                changed.html = New.html



    def clear(self):
        _translate = QtCore.QCoreApplication.translate
        self.html = ''
        self.list = []
        self.len = 0
        self.textlist = []
        self.B_im = False
        self.B_label = False
        self.paragraph = 0
        self.done = False
        self.color.name=""
        self.color.html="#ffffff"
        self.B_Background.int=-1
        self.backgroundImage=''
        self.background.name=""
        self.background.html=""
        self.BorderColor.html="#ffffff"
        self.BorderColor.name=""
        self.Margin.setText("default")
        self.label_29.setText( "0123456789abcdefghijklmnopgrstuvwxyz")
        self.C_Font.setCurrentIndex(0)
        self.BorderRad.setText( "0")
        self.Border_Wid.setText("0")
        self.padding_2.setText( "default")
        self.Size.setCurrentIndex(0)
        self.Height.setText("default")
        self.Width.setText( "default")
        self.Text.setText("")
        self.Bold.setChecked(False)
        self.Italic.setChecked(False)
        self.Small.setChecked(False)
        self.Sub.setChecked(False)
        self.Sup.setChecked(False)
        self.Delete.setChecked(False)
        self.Mark.setChecked(False)
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.RepeatX.setChecked(False)
        self.RepeatY.setChecked(False)

    def textWrite(self):
        cursor=self.Text.textCursor()
        i=cursor.position()

        if(len(self.Text.toPlainText())>self.len):

            self.len=self.len + 1
            info=[self.Bold.isChecked(),self.Italic.isChecked(),self.Mark.isChecked(),self.Small.isChecked(),self.Sub.isChecked(),self.Sup.isChecked(),self.Delete.isChecked()]
            self.list.insert(i,info)
            text = self.Text.toPlainText()
            New = text[i-1]
            TabList=[['<b>','</b>'],['<i>','</i>'],['<span style="background-color: yellow;">','</span>'],['<small>','</small>'],['<sub>','</sub>'],['<sup>','</sup>'],['<span style="text-decoration:line-through;">','</span>']]
            if(len(text)>=i and text[i - 1] == "\n"):
                New="<br>"
            else:
                for f in range(7):
                    if info[f]:
                        New=TabList[f][0]+New+TabList[f][1]

            self.textlist.insert(i-1,New)
            text=''
            for z in self.textlist:
                text+=z

            self.Text.setText(text)
            cursor=self.Text.textCursor()
            cursor.movePosition(QtGui.QTextCursor.MoveOperation.Right,n=i)
            self.Text.setTextCursor(cursor)
            self.Text.setFocus()

        elif(len(self.Text.toPlainText())<self.len):
            self.list.pop(i)
            self.textlist.pop(i)
            self.len=self.len-1

