# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'link.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Function import *
import shutil
from Class import*


class Ui_Link(object):
    def setupUi(self, Link):
        self.done=False
        self.BFile=-1
        self.Text=''
        Link.setObjectName("Link")
        Link.resize(393, 160)
        self.Name=''
        self.label = QtWidgets.QLabel(Link)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Link)
        self.lineEdit.setGeometry(QtCore.QRect(80, 30, 281, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.Finish = QtWidgets.QPushButton(Link)
        self.Finish.setGeometry(QtCore.QRect(280, 100, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Cancel = QtWidgets.QPushButton(Link)
        self.Cancel.setGeometry(QtCore.QRect(170, 100, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.TextFile = QtWidgets.QPushButton(Link)
        self.TextFile.setGeometry(QtCore.QRect(80, 60, 281, 28))
        self.TextFile.setObjectName("TextFile")
        self.TextFile.clicked.connect(self.Search)
        self.lineEdit.textChanged.connect(self.TextChanged)
        self.retranslateUi(Link)
        QtCore.QMetaObject.connectSlotsByName(Link)

    def retranslateUi(self, Link):
        _translate = QtCore.QCoreApplication.translate
        Link.setWindowTitle(_translate("Link", "Link"))
        self.label.setText(_translate("Link", "Link:"))
        self.Finish.setText(_translate("Link", "Finish"))
        self.Cancel.setText(_translate("Link", "Cancel"))
        self.TextFile.setText(_translate("Link", "Use TextFile"))
    def Search(self):
        text=searching(TEXTFILEINDEX,self.Name)
        if text!=False:
            self.BFile=True
            self.Text=text
            self.lineEdit.hide()
    def TextChanged(self):
        self.BFile=False
        self.Text=self.lineEdit.text()
        self.TextFile.hide()




