# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paragraphInfoWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Function import *
import shutil
from Class import*

class Ui_ParagraphWin(object):
    def setupUi(self, ParagraphWin,searchingColor):
        ParagraphWin.setObjectName("ParagraphWin")
        ParagraphWin.resize(635, 995)

        self.Name=''
        self.SearchingColor=searchingColor
        self.html=''
        self.list=[]
        self.len=0
        self.textlist=[]
        self.B_im=False
        self.B_label=False
        self.paragraph=0
        self.done=False

        self.centralwidget=ParagraphWin
        self.information2 = QtWidgets.QPushButton(self.centralwidget)
        self.information2.setGeometry(QtCore.QRect(350, 500, 111, 28))
        self.information2.setObjectName("information2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(60, 630, 131, 16))
        self.label_16.setObjectName("label_16")
        self.Margin = QtWidgets.QLineEdit(self.centralwidget)
        self.Margin.setGeometry(QtCore.QRect(200, 500, 113, 21))
        self.Margin.setObjectName("Margin")
        self.RepeatX = QtWidgets.QCheckBox(self.centralwidget)
        self.RepeatX.setGeometry(QtCore.QRect(110, 350, 115, 19))
        self.RepeatX.setObjectName("RepeatX")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 351, 16))
        self.label_3.setObjectName("label_3")
        self.ColorPaleet_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ColorPaleet_2.setGeometry(QtCore.QRect(350, 630, 211, 28))
        self.ColorPaleet_2.setObjectName("ColorPaleet_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 111, 16))
        self.label_4.setObjectName("label_4")
        self.information = QtWidgets.QPushButton(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(350, 460, 111, 28))
        self.information.setObjectName("information")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(320, 460, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 540, 72, 15))
        self.label_12.setObjectName("label_12")
        self.R_Top = QtWidgets.QCheckBox(self.centralwidget)
        self.R_Top.setGeometry(QtCore.QRect(60, 710, 71, 19))
        self.R_Top.setObjectName("R_Top")
        self.R_Left = QtWidgets.QCheckBox(self.centralwidget)
        self.R_Left.setGeometry(QtCore.QRect(180, 710, 71, 19))
        self.R_Left.setObjectName("R_Left")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(400, 930, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(60, 670, 121, 16))
        self.label_19.setObjectName("label_19")
        self.BorderRad = QtWidgets.QLineEdit(self.centralwidget)
        self.BorderRad.setGeometry(QtCore.QRect(200, 670, 113, 21))
        self.BorderRad.setObjectName("BorderRad")
        self.ColorName = QtWidgets.QPushButton(self.centralwidget)
        self.ColorName.setGeometry(QtCore.QRect(110, 300, 141, 28))
        self.ColorName.setObjectName("ColorName")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 300, 72, 15))
        self.label_7.setObjectName("label_7")
        self.R_Bottom = QtWidgets.QCheckBox(self.centralwidget)
        self.R_Bottom.setGeometry(QtCore.QRect(430, 710, 71, 19))
        self.R_Bottom.setObjectName("R_Bottom")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 260, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 16))
        self.label.setObjectName("label")
        self.ColorName_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ColorName_2.setGeometry(QtCore.QRect(200, 630, 141, 28))
        self.ColorName_2.setObjectName("ColorName_2")
        self.ColorPaleet = QtWidgets.QPushButton(self.centralwidget)
        self.ColorPaleet.setGeometry(QtCore.QRect(260, 300, 211, 28))
        self.ColorPaleet.setObjectName("ColorPaleet")
        self.Font = QtWidgets.QComboBox(self.centralwidget)
        self.Font.setGeometry(QtCore.QRect(150, 50, 231, 22))
        self.Font.setObjectName("Font")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.Font.addItem("")
        self.information3 = QtWidgets.QPushButton(self.centralwidget)
        self.information3.setGeometry(QtCore.QRect(350, 570, 111, 28))
        self.information3.setObjectName("information3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 420, 141, 16))
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(320, 600, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 460, 72, 15))
        self.label_9.setObjectName("label_9")
        self.C_BorderStyle = QtWidgets.QComboBox(self.centralwidget)
        self.C_BorderStyle.setGeometry(QtCore.QRect(200, 570, 111, 22))
        self.C_BorderStyle.setObjectName("C_BorderStyle")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.C_BorderStyle.addItem("")
        self.Finish = QtWidgets.QPushButton(self.centralwidget)
        self.Finish.setGeometry(QtCore.QRect(510, 930, 93, 28))
        self.Finish.setObjectName("Finish")
        self.B_SearchImage = QtWidgets.QPushButton(self.centralwidget)
        self.B_SearchImage.setGeometry(QtCore.QRect(380, 260, 21, 28))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.B_SearchImage.setFont(font)
        self.B_SearchImage.setObjectName("B_SearchImage")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(320, 670, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 500, 72, 15))
        self.label_10.setObjectName("label_10")
        self.Border_Wid = QtWidgets.QLineEdit(self.centralwidget)
        self.Border_Wid.setGeometry(QtCore.QRect(200, 600, 113, 21))
        self.Border_Wid.setObjectName("Border_Wid")
        self.R_Right = QtWidgets.QCheckBox(self.centralwidget)
        self.R_Right.setGeometry(QtCore.QRect(310, 710, 71, 19))
        self.R_Right.setObjectName("R_Right")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(60, 570, 131, 16))
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(320, 500, 16, 16))
        self.label_18.setObjectName("label_18")
        self.RepeatY = QtWidgets.QCheckBox(self.centralwidget)
        self.RepeatY.setGeometry(QtCore.QRect(110, 380, 115, 19))
        self.RepeatY.setObjectName("RepeatY")
        self.C_Align = QtWidgets.QComboBox(self.centralwidget)
        self.C_Align.setGeometry(QtCore.QRect(200, 420, 121, 22))
        self.C_Align.setObjectName("C_Align")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.C_Align.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(60, 600, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 72, 15))
        self.label_5.setObjectName("label_5")
        self.B_image = QtWidgets.QPushButton(self.centralwidget)
        self.B_image.setGeometry(QtCore.QRect(420, 260, 61, 28))
        self.B_image.setObjectName("B_image")
        self.padding = QtWidgets.QLineEdit(self.centralwidget)
        self.padding.setGeometry(QtCore.QRect(200, 460, 113, 21))
        self.padding.setObjectName("padding")
        self.FontSize = QtWidgets.QLineEdit(self.centralwidget)
        self.FontSize.setGeometry(QtCore.QRect(150, 20, 113, 21))
        self.FontSize.setObjectName("FontSize")
        self.C_FontSizeU = QtWidgets.QComboBox(self.centralwidget)
        self.C_FontSizeU.setGeometry(QtCore.QRect(280, 20, 87, 22))
        self.C_FontSizeU.setObjectName("C_FontSizeU")
        self.C_FontSizeU.addItem("")
        self.C_FontSizeU.addItem("")
        self.C_FontSizeU.addItem("")
        self.Text = QtWidgets.QTextEdit(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(20, 800, 541, 111))
        self.Text.setObjectName("Text")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 740, 72, 15))
        self.label_11.setObjectName("label_11")
        self.C_HeightWidthU = QtWidgets.QComboBox(self.centralwidget)
        self.C_HeightWidthU.setGeometry(QtCore.QRect(400, 120, 87, 22))
        self.C_HeightWidthU.setObjectName("C_HeightWidthU")
        self.C_HeightWidthU.addItem("")
        self.C_HeightWidthU.addItem("")
        self.C_HeightWidthU.addItem("")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(30, 120, 121, 16))
        self.label_21.setObjectName("label_21")
        self.Height = QtWidgets.QLineEdit(self.centralwidget)
        self.Height.setGeometry(QtCore.QRect(270, 120, 113, 21))
        self.Height.setObjectName("Height")
        self.Bold = QtWidgets.QPushButton(self.centralwidget)
        self.Bold.setGeometry(QtCore.QRect(20, 770, 51, 31))
        self.Bold.setObjectName("Bold")
        self.Italic = QtWidgets.QPushButton(self.centralwidget)
        self.Italic.setGeometry(QtCore.QRect(70, 770, 61, 31))
        self.Italic.setObjectName("Italic")
        self.Mark = QtWidgets.QPushButton(self.centralwidget)
        self.Mark.setGeometry(QtCore.QRect(130, 770, 61, 31))
        self.Mark.setObjectName("Mark")
        self.Small = QtWidgets.QPushButton(self.centralwidget)
        self.Small.setGeometry(QtCore.QRect(190, 770, 61, 31))
        self.Small.setObjectName("Small")
        self.Sub = QtWidgets.QPushButton(self.centralwidget)
        self.Sub.setGeometry(QtCore.QRect(250, 770, 41, 31))
        self.Sub.setObjectName("Sub")
        self.Sup = QtWidgets.QPushButton(self.centralwidget)
        self.Sup.setGeometry(QtCore.QRect(290, 770, 41, 31))
        self.Sup.setObjectName("Sup")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(330, 770, 41, 31))
        self.Delete.setObjectName("Delete")
        self.information4 = QtWidgets.QPushButton(self.centralwidget)
        self.information4.setGeometry(QtCore.QRect(440, 770, 121, 31))
        self.information4.setObjectName("information4")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(170, 120, 72, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(170, 150, 72, 16))
        self.label_23.setObjectName("label_23")
        self.Width = QtWidgets.QLineEdit(self.centralwidget)
        self.Width.setGeometry(QtCore.QRect(270, 150, 113, 21))
        self.Width.setObjectName("Width")
        self.C_HeightWidthU_2 = QtWidgets.QComboBox(self.centralwidget)
        self.C_HeightWidthU_2.setGeometry(QtCore.QRect(400, 150, 87, 22))
        self.C_HeightWidthU_2.setObjectName("C_HeightWidthU_2")
        self.C_HeightWidthU_2.addItem("")
        self.C_HeightWidthU_2.addItem("")
        self.C_HeightWidthU_2.addItem("")
        self.information5 = QtWidgets.QPushButton(self.centralwidget)
        self.information5.setGeometry(QtCore.QRect(500, 120, 101, 51))
        self.information5.setObjectName("information5")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(30, 190, 72, 15))
        self.label_24.setObjectName("label_24")
        self.ColorName_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ColorName_3.setGeometry(QtCore.QRect(90, 190, 141, 28))
        self.ColorName_3.setObjectName("ColorName_3")
        self.ColorPaleet_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ColorPaleet_3.setGeometry(QtCore.QRect(240, 190, 211, 28))
        self.ColorPaleet_3.setObjectName("ColorPaleet_3")

    ################################
        self.color = Color()
        self.color.name = ""
        self.color.html = "#ffffff"
        self.B_Background = MyInt(-1)
        self.background = Color()
        self.BorderColor = Color()
        self.BorderColor.html = "#ffffff"
        self.BorderColor.name = ""
        self.backgroundImage=''
        self.Bold.setCheckable(True)
        self.Italic.setCheckable(True)
        self.Sub.setCheckable(True)
        self.Sup.setCheckable(True)
        self.Small.setCheckable(True)
        self.Delete.setCheckable(True)
        self.Mark.setCheckable(True)

        ####################################################

        self.retranslateUi(ParagraphWin)
        QtCore.QMetaObject.connectSlotsByName(ParagraphWin)

    def retranslateUi(self, ParagraphWin):
        _translate = QtCore.QCoreApplication.translate
        ParagraphWin.setWindowTitle(_translate("ParagraphWin", "Paragraph information window"))
        self.information2.setText(_translate("ParagraphWin", "information"))
        self.label_16.setText(_translate("ParagraphWin", "Border Color:"))
        self.Margin.setText(_translate("ParagraphWin", "default"))
        self.RepeatX.setText(_translate("ParagraphWin", "Repeat x"))
        self.label_3.setText(_translate("ParagraphWin", "0123456789abcdefghijklmnopgrstuvwxyz"))
        self.ColorPaleet_2.setText(_translate("ParagraphWin", "choose by Colour Paleet"))
        self.label_4.setText(_translate("ParagraphWin", "background:"))
        self.information.setText(_translate("ParagraphWin", "information"))
        self.label_17.setText(_translate("ParagraphWin", "px"))
        self.label_2.setText(_translate("ParagraphWin", "Font:"))
        self.label_12.setText(_translate("ParagraphWin", "Border:"))
        self.R_Top.setText(_translate("ParagraphWin", "Top"))
        self.R_Left.setText(_translate("ParagraphWin", "Left"))
        self.Cancel.setText(_translate("ParagraphWin", "Cancel"))#
        self.label_19.setText(_translate("ParagraphWin", "Border Radius:"))
        self.BorderRad.setText(_translate("ParagraphWin", "0"))
        self.ColorName.setText(_translate("ParagraphWin", "choose by name"))
        self.label_7.setText(_translate("ParagraphWin", "Color:"))
        self.R_Bottom.setText(_translate("ParagraphWin", "Bottom"))
        self.label_6.setText(_translate("ParagraphWin", "imageName"))
        self.label.setText(_translate("ParagraphWin", "Font Size:"))
        self.ColorName_2.setText(_translate("ParagraphWin", "choose by name"))
        self.ColorPaleet.setText(_translate("ParagraphWin", "choose by Colour Paleet"))
        self.Font.setItemText(0, _translate("ParagraphWin", "Arial (sans-serif)"))
        self.Font.setItemText(1, _translate("ParagraphWin", "Verdana (sans-serif)"))
        self.Font.setItemText(2, _translate("ParagraphWin", "Helvetica (sans-serif)"))
        self.Font.setItemText(3, _translate("ParagraphWin", "Tahoma (sans-serif)"))
        self.Font.setItemText(4, _translate("ParagraphWin", "Trebuchet MS (sans-serif)"))
        self.Font.setItemText(5, _translate("ParagraphWin", "Times New Roman (serif)"))
        self.Font.setItemText(6, _translate("ParagraphWin", "Georgia (serif)"))
        self.Font.setItemText(7, _translate("ParagraphWin", "Garamond (serif)"))
        self.Font.setItemText(8, _translate("ParagraphWin", "Courier New (monospace)"))
        self.Font.setItemText(9, _translate("ParagraphWin", "Brush Script MT (cursive)"))
        self.information3.setText(_translate("ParagraphWin", "information"))
        self.label_8.setText(_translate("ParagraphWin", "Text Alignment:"))
        self.label_15.setText(_translate("ParagraphWin", "px"))
        self.label_9.setText(_translate("ParagraphWin", "Padding:"))
        self.C_BorderStyle.setItemText(0, _translate("ParagraphWin", "none"))
        self.C_BorderStyle.setItemText(1, _translate("ParagraphWin", "dotted"))
        self.C_BorderStyle.setItemText(2, _translate("ParagraphWin", "dashed"))
        self.C_BorderStyle.setItemText(3, _translate("ParagraphWin", "solid"))
        self.C_BorderStyle.setItemText(4, _translate("ParagraphWin", "double"))
        self.C_BorderStyle.setItemText(5, _translate("ParagraphWin", "groove"))
        self.C_BorderStyle.setItemText(6, _translate("ParagraphWin", "ridge"))
        self.C_BorderStyle.setItemText(7, _translate("ParagraphWin", "inset"))
        self.C_BorderStyle.setItemText(8, _translate("ParagraphWin", "outset"))
        self.C_BorderStyle.setItemText(9, _translate("ParagraphWin", "hidden"))
        self.Finish.setText(_translate("ParagraphWin", "Finish"))
        self.B_SearchImage.setText(_translate("ParagraphWin", "⋮"))
        self.label_20.setText(_translate("ParagraphWin", "px"))
        self.label_10.setText(_translate("ParagraphWin", "Margin:"))
        self.Border_Wid.setText(_translate("ParagraphWin", "0"))
        self.R_Right.setText(_translate("ParagraphWin", "Right"))
        self.label_13.setText(_translate("ParagraphWin", "Border Style:"))
        self.label_18.setText(_translate("ParagraphWin", "px"))
        self.RepeatY.setText(_translate("ParagraphWin", "Repeat y"))
        self.C_Align.setItemText(0, _translate("ParagraphWin", "justify"))
        self.C_Align.setItemText(1, _translate("ParagraphWin", "right"))
        self.C_Align.setItemText(2, _translate("ParagraphWin", "left"))
        self.C_Align.setItemText(3, _translate("ParagraphWin", "center"))
        self.label_14.setText(_translate("ParagraphWin", "Border Width:"))
        self.label_5.setText(_translate("ParagraphWin", "image:"))
        self.B_image.setText(_translate("ParagraphWin", "apply"))
        self.padding.setText(_translate("ParagraphWin", "default"))
        self.FontSize.setText(_translate("ParagraphWin", "default"))
        self.C_FontSizeU.setItemText(0, _translate("ParagraphWin", "px"))
        self.C_FontSizeU.setItemText(1, _translate("ParagraphWin", "%"))
        self.C_FontSizeU.setItemText(2, _translate("ParagraphWin", "em"))
        self.Text.setText("")
        self.label_11.setText(_translate("ParagraphWin", "Text:"))
        self.C_HeightWidthU.setItemText(0, _translate("ParagraphWin", "px"))
        self.C_HeightWidthU.setItemText(1, _translate("ParagraphWin", "%"))
        self.C_HeightWidthU.setItemText(2, _translate("ParagraphWin", "em"))
        self.label_21.setText(_translate("ParagraphWin", "Height/width:"))
        self.Height.setText(_translate("ParagraphWin", "default"))
        self.Bold.setText(_translate("ParagraphWin", "Bold"))
        self.Italic.setText(_translate("ParagraphWin", "Italic"))
        self.Mark.setText(_translate("ParagraphWin", "Marked"))
        self.Small.setText(_translate("ParagraphWin", "Small"))
        self.Sub.setText(_translate("ParagraphWin", "Sub"))
        self.Sup.setText(_translate("ParagraphWin", "Sup"))
        self.Delete.setText(_translate("ParagraphWin", "del"))
        self.information4.setText(_translate("ParagraphWin", "information"))
        self.label_22.setText(_translate("aragraphWin", "Height:"))
        self.label_23.setText(_translate("ParagraphWin", "Width:"))
        self.Width.setText(_translate("ParagraphWin", "default"))
        self.C_HeightWidthU_2.setItemText(0, _translate("ParagraphWin", "px"))
        self.C_HeightWidthU_2.setItemText(1, _translate("ParagraphWin", "%"))
        self.C_HeightWidthU_2.setItemText(2, _translate("ParagraphWin", "em"))
        self.information5.setText(_translate("ParagraphWin", "information"))
        self.label_24.setText(_translate("ParagraphWin", "Color:"))
        self.ColorName_3.setText(_translate("ParagraphWin", "choose by name"))
        self.ColorPaleet_3.setText(_translate("ParagraphWin", "choose by Colour Paleet"))
        ##############################
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.Text.setText("")
        self.Text.textChanged.connect(self.textWrite)
        self.Text.cursorPositionChanged.connect(self.CursorChanged)
        self.B_image.clicked.connect(self.ImageApply)
        self.Bold.clicked.connect(self.Press)
        self.Italic.clicked.connect(self.Press)
        self.Small.clicked.connect(self.Press)
        self.Sub.clicked.connect(self.Press)
        self.Sup.clicked.connect(self.Press)
        self.Delete.clicked.connect(self.Press)
        self.Mark.clicked.connect(self.Press)
        self.B_SearchImage.clicked.connect(self.seach_image)
        self.ColorPaleet.clicked.connect(lambda state, x=self.background,y=self.B_Background: self.ClickColor1(x,y))
        self.ColorName.clicked.connect(lambda state, x=self.background,y=self.B_Background: self.ChooseColorByName1(x,y))
        self.ColorPaleet_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ClickColor1(x,y))
        self.ColorName_2.clicked.connect(lambda state, x=self.BorderColor,y="default": self.ChooseColorByName1(x,y))
        self.ColorPaleet_3.clicked.connect(lambda state, x=self.color,y="default": self.ClickColor1(x,y))
        self.ColorName_3.clicked.connect(lambda state, x=self.color,y="default": self.ChooseColorByName1(x,y))
        self.information.clicked.connect(lambda state, x="The CSS padding properties are used to generate space around an element's content, inside of any defined borders. it is editted as padding:PADDING WIDTH px inside Style.":Information(x))
        self.information2.clicked.connect(lambda state, x="The CSS margin properties are used to create space around elements, outside of any defined borders. it is editted as margin:MARGIN WIDTH px inside Style.":Information(x))
        self.information3.clicked.connect(lambda state,x="Borders style,Border Width,Border color,border radius can be edited as border-style:BORDER STYLE;border-width:WIDTH px;border-radius:RADIUS px; border style is set for rounded borders":Information(x))
        self.information4.clicked.connect(lambda state,
                                                 x="HTML contains several elements for defining text with a special meaning.\n<b> - Bold text\n<strong> - Important text\n<i> - Italic text\n<em> - Emphasized text\n<mark> - Marked text\n<small> - Smaller text\n<del> - Deleted text\n<ins> - Inserted text\n<sub> - Subscript text\n<sup> - Superscript text\n strong bold have the same functions, and italic and em are of the same functions as well ": Information(x))
        self.information5.clicked.connect(lambda state,x="for size which is not enough to repersent texts, in html it can show the whole texts out as well, but in pyqt5 it can just show the part of texts which is limited by width and height": Information(x))
        self.label_3.setFont(QtGui.QFont(self.Font.currentText().split(" (")[0]))
        self.Font.currentIndexChanged.connect(self.FontChanged)
    def seach_image(self):
        file=searching(IMAGEINDEX,self.Name)
        if file!="":
            self.label_6.setText(file.split("/")[-1])
            self.B_im=True
            self.backgroundImage=file
    def ImageApply(self):
        if (self.B_im):
            self.B_Background.int=0
        else:
            Warning("The image file have not be set yet.")
    def ChooseColorByName1(self,changed,boolean):
        New=self.GetColor()
        if(New):
            if(boolean!="default"):
                boolean.int = 1
                changed.html=New.html
                changed.name=New.name
            else:
                changed.html=New.html
                changed.name=New.name





    def GetColor(self):
        New = Color()
        self.SearchingColor.Repersent(New)
        if (New.name != ''):
            return New
        else:
            return False

    #def ChooseColByName(self):




    def CursorChanged(self):
        cursor=self.Text.textCursor()##delete the selection of text
        if len(cursor.selectedText())>1:
            cursor.clearSelection()
            self.Text.setTextCursor(cursor)
            self.Text.setFocus()
    def Press(self):
        self.Text.setFocus()
    def ClickColor1(self,changed,boolea):

        New=openColorDialog()
        if (New):
            if (boolea !="default"):

                boolea.int = 1
                changed.name = New.name
                changed.html=New.html
            else:
                changed.name = New.name
                changed.html = New.html



    def clear(self):
        _translate = QtCore.QCoreApplication.translate
        self.html = ''
        self.list = []
        self.len = 0
        self.textlist = []
        self.B_im = False
        self.B_label = False
        self.paragraph = 0
        self.done = False
        self.color.name=""
        self.color.html="#ffffff"
        self.B_Background.int=-1
        self.background.name=""
        self.background.html=""
        self.backgroundImage=''
        self.BorderColor.html="#ffffff"
        self.BorderColor.name=""
        self.Margin.setText("default")
        self.label_3.setText(_translate("ParagraphWin", "0123456789abcdefghijklmnopgrstuvwxyz"))
        self.BorderRad.setText(_translate("ParagraphWin", "0"))
        self.Border_Wid.setText(_translate("ParagraphWin", "0"))
        self.padding.setText(_translate("ParagraphWin", "default"))
        self.FontSize.setText(_translate("ParagraphWin", "default"))
        self.Height.setText(_translate("ParagraphWin", "default"))
        self.Width.setText(_translate("ParagraphWin", "default"))
        self.Font.setCurrentIndex(0)
        self.Text.setText("")
        self.Bold.setChecked(False)
        self.Italic.setChecked(False)
        self.Small.setChecked(False)
        self.Sub.setChecked(False)
        self.Sup.setChecked(False)
        self.Delete.setChecked(False)
        self.Mark.setChecked(False)
        self.R_Top.setChecked(True)
        self.R_Left.setChecked(True)
        self.R_Right.setChecked(True)
        self.R_Bottom.setChecked(True)
        self.RepeatX.setChecked(False)
        self.RepeatY.setChecked(False)
    def FontChanged(self,int):
        self.label_3.setFont(QtGui.QFont(self.Font.currentText().split(" (")[0]))


    def textWrite(self):
        cursor=self.Text.textCursor()
        i=cursor.position()

        if(len(self.Text.toPlainText())>self.len):

            self.len=self.len + 1
            info=[self.Bold.isChecked(),self.Italic.isChecked(),self.Mark.isChecked(),self.Small.isChecked(),self.Sub.isChecked(),self.Sup.isChecked(),self.Delete.isChecked()]
            self.list.insert(i,info)
            text = self.Text.toPlainText()
            New = text[i-1]
            TabList=[['<b>','</b>'],['<i>','</i>'],['<span style="background-color: yellow;">','</span>'],['<small>','</small>'],['<sub>','</sub>'],['<sup>','</sup>'],['<span style="text-decoration:line-through;">','</span>']]
            if(len(text)>=i and text[i - 1] == "\n"):
                New="<br>"
            else:
                for f in range(7):
                    if info[f]:
                        New=TabList[f][0]+New+TabList[f][1]

            self.textlist.insert(i-1,New)
            text=''
            for z in self.textlist:
                text+=z

            self.Text.setText(text)
            cursor=self.Text.textCursor()
            cursor.movePosition(QtGui.QTextCursor.MoveOperation.Right,n=i)
            self.Text.setTextCursor(cursor)
            self.Text.setFocus()

        elif(len(self.Text.toPlainText())<self.len):
            self.list.pop(i)
            self.textlist.pop(i)
            self.len=self.len-1
