# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picture.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Function import *
import shutil
from Class import*

class Ui_Picture(object):
    def setupUi(self, Picture):
        Picture.setObjectName("Picture")
        Picture.resize(429, 132)
        self.name=""
        self.done=False
        self.File=''
        self.picture=''
        self.label_48 = QtWidgets.QLabel(Picture)
        self.label_48.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_48.setObjectName("label_48")
        self.B_SearchImage_2 = QtWidgets.QPushButton(Picture)
        self.B_SearchImage_2.setGeometry(QtCore.QRect(380, 30, 21, 28))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.B_SearchImage_2.setFont(font)
        self.B_SearchImage_2.setObjectName("B_SearchImage_2")
        self.label_47 = QtWidgets.QLabel(Picture)
        self.label_47.setGeometry(QtCore.QRect(80, 30, 191, 16))
        self.label_47.setObjectName("label_47")
        self.Finish = QtWidgets.QPushButton(Picture)
        self.Finish.setGeometry(QtCore.QRect(310, 80, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Cancel = QtWidgets.QPushButton(Picture)
        self.Cancel.setGeometry(QtCore.QRect(200, 80, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.B_SearchImage_2.clicked.connect(self.Search)
        self.retranslateUi(Picture)

        QtCore.QMetaObject.connectSlotsByName(Picture)

    def retranslateUi(self, Picture):
        _translate = QtCore.QCoreApplication.translate
        Picture.setWindowTitle(_translate("Picture", "Picture"))
        self.label_48.setText(_translate("Picture", "image:"))
        self.B_SearchImage_2.setText(_translate("Picture", "⋮"))
        self.label_47.setText(_translate("Picture", "imageName"))
        self.Finish.setText(_translate("Picture", "Finish"))
        self.Cancel.setText(_translate("Picture", "Cancel"))
    def Search(self):
        self.File=searching(IMAGEINDEX,self.name)
        if(self.File!=""):
            self.label_47.setText(self.File.split("/")[-1])
    def clear(self):
        self.File=""
        self.label_47.setText("imageName")
        self.done=False



