# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectName.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectName(object):
    def setupUi(self, ProjectName):
        ProjectName.setObjectName("ProjectName")
        ProjectName.resize(437, 71)
        self.name = QtWidgets.QLineEdit(ProjectName)
        self.name.setGeometry(QtCore.QRect(30, 20, 271, 21))
        self.name.setObjectName("name")
        self.pushButton = QtWidgets.QPushButton(ProjectName)
        self.pushButton.setGeometry(QtCore.QRect(330, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ProjectName)
        QtCore.QMetaObject.connectSlotsByName(ProjectName)

    def retranslateUi(self, ProjectName):
        _translate = QtCore.QCoreApplication.translate
        ProjectName.setWindowTitle(_translate("ProjectName", "Project Name"))
        self.pushButton.setText(_translate("ProjectName", "Set"))
