# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quote.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Quote(object):
    def setupUi(self, Quote):
        Quote.setObjectName("Quote")
        Quote.resize(591, 309)
        self.Italic = QtWidgets.QPushButton(Quote)
        self.Italic.setGeometry(QtCore.QRect(70, 50, 61, 31))
        self.Italic.setObjectName("Italic")
        self.Delete = QtWidgets.QPushButton(Quote)
        self.Delete.setGeometry(QtCore.QRect(330, 50, 41, 31))
        self.Delete.setObjectName("Delete")
        self.Small = QtWidgets.QPushButton(Quote)
        self.Small.setGeometry(QtCore.QRect(190, 50, 61, 31))
        self.Small.setObjectName("Small")
        self.Bold = QtWidgets.QPushButton(Quote)
        self.Bold.setGeometry(QtCore.QRect(20, 50, 51, 31))
        self.Bold.setObjectName("Bold")
        self.Text = QtWidgets.QLineEdit(Quote)
        self.Text.setGeometry(QtCore.QRect(20, 80, 541, 111))
        self.Text.setObjectName("Text")
        self.information4 = QtWidgets.QPushButton(Quote)
        self.information4.setGeometry(QtCore.QRect(440, 50, 121, 31))
        self.information4.setObjectName("information4")
        self.Sup = QtWidgets.QPushButton(Quote)
        self.Sup.setGeometry(QtCore.QRect(290, 50, 41, 31))
        self.Sup.setObjectName("Sup")
        self.Finish = QtWidgets.QPushButton(Quote)
        self.Finish.setGeometry(QtCore.QRect(460, 250, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Mark = QtWidgets.QPushButton(Quote)
        self.Mark.setGeometry(QtCore.QRect(130, 50, 61, 31))
        self.Mark.setObjectName("Mark")
        self.label_31 = QtWidgets.QLabel(Quote)
        self.label_31.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_31.setObjectName("label_31")
        self.Sub = QtWidgets.QPushButton(Quote)
        self.Sub.setGeometry(QtCore.QRect(250, 50, 41, 31))
        self.Sub.setObjectName("Sub")
        self.Cancel = QtWidgets.QPushButton(Quote)
        self.Cancel.setGeometry(QtCore.QRect(350, 250, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.label = QtWidgets.QLabel(Quote)
        self.label.setGeometry(QtCore.QRect(20, 210, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Quote)
        self.lineEdit.setGeometry(QtCore.QRect(70, 210, 481, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Quote)
        QtCore.QMetaObject.connectSlotsByName(Quote)

    def retranslateUi(self, Quote):
        _translate = QtCore.QCoreApplication.translate
        Quote.setWindowTitle(_translate("Quote", "Quote"))
        self.Italic.setText(_translate("Quote", "Italic"))
        self.Delete.setText(_translate("Quote", "del"))
        self.Small.setText(_translate("Quote", "Small"))
        self.Bold.setText(_translate("Quote", "Bold"))
        self.information4.setText(_translate("Quote", "information"))
        self.Sup.setText(_translate("Quote", "Sup"))
        self.Finish.setText(_translate("Quote", "Finish"))
        self.Mark.setText(_translate("Quote", "Marked"))
        self.label_31.setText(_translate("Quote", "Text:"))
        self.Sub.setText(_translate("Quote", "Sub"))
        self.Cancel.setText(_translate("Quote", "Cancel"))
        self.label.setText(_translate("Quote", "cite:"))
