# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectingMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectMode(object):
    def setupUi(self, SelectMode):
        SelectMode.setObjectName("SelectMode")
        SelectMode.resize(300, 153)
        self.pushButton = QtWidgets.QPushButton(SelectMode)
        self.pushButton.setGeometry(QtCore.QRect(50, 30, 201, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(SelectMode)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 80, 201, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(SelectMode)
        QtCore.QMetaObject.connectSlotsByName(SelectMode)

    def retranslateUi(self, SelectMode):
        _translate = QtCore.QCoreApplication.translate
        SelectMode.setWindowTitle(_translate("SelectMode", "Selecting mode"))
        self.pushButton.setText(_translate("SelectMode", "Choose Locally"))
        self.pushButton_2.setText(_translate("SelectMode", "Choose From Cloud"))
