# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.resize(392, 180)
        self.Finish = QtWidgets.QPushButton(SignIn)
        self.Finish.setGeometry(QtCore.QRect(280, 140, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Cancel = QtWidgets.QPushButton(SignIn)
        self.Cancel.setGeometry(QtCore.QRect(170, 140, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.label = QtWidgets.QLabel(SignIn)
        self.label.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label.setObjectName("label")
        self.UserID = QtWidgets.QLineEdit(SignIn)
        self.UserID.setGeometry(QtCore.QRect(120, 30, 221, 21))
        self.UserID.setObjectName("UserID")
        self.label_2 = QtWidgets.QLabel(SignIn)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.Password = QtWidgets.QLineEdit(SignIn)
        self.Password.setGeometry(QtCore.QRect(120, 70, 221, 21))
        self.Password.setObjectName("Password")
        self.label_3 = QtWidgets.QLabel(SignIn)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 261, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(SignIn)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "SignIn"))
        self.Finish.setText(_translate("SignIn", "Finish"))
        self.Cancel.setText(_translate("SignIn", "Cancel"))
        self.label.setText(_translate("SignIn", "UserID:"))
        self.label_2.setText(_translate("SignIn", "Password:"))
        self.label_3.setText(_translate("SignIn", "Please input UserID and Password"))
