# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWin(object):
    def setupUi(self, StartWin):
        StartWin.setObjectName("StartWin")
        StartWin.resize(411, 182)
        self.centralwidget = QtWidgets.QWidget(StartWin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 30, 261, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 70, 261, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 110, 261, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        StartWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StartWin)
        self.statusbar.setObjectName("statusbar")
        StartWin.setStatusBar(self.statusbar)

        self.retranslateUi(StartWin)
        QtCore.QMetaObject.connectSlotsByName(StartWin)

    def retranslateUi(self, StartWin):
        _translate = QtCore.QCoreApplication.translate
        StartWin.setWindowTitle(_translate("StartWin", "Start Window"))
        self.pushButton.setText(_translate("StartWin", "Regist"))
        self.pushButton_2.setText(_translate("StartWin", "Sign in"))
        self.pushButton_3.setText(_translate("StartWin", "Use as visitor"))


