# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Function import *
import shutil
from Class import*

class Ui_Video(object):
    def setupUi(self, Video):
        self.Name=''

        Video.setObjectName("Video")
        Video.resize(397, 135)
        self.B_SearchImage = QtWidgets.QPushButton(Video)
        self.B_SearchImage.setGeometry(QtCore.QRect(350, 30, 21, 28))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.B_SearchImage.setFont(font)
        self.B_SearchImage.setObjectName("B_SearchImage")
        self.label_42 = QtWidgets.QLabel(Video)
        self.label_42.setGeometry(QtCore.QRect(80, 30, 191, 16))
        self.label_42.setObjectName("label_42")
        self.label_34 = QtWidgets.QLabel(Video)
        self.label_34.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_34.setObjectName("label_34")
        self.Finish = QtWidgets.QPushButton(Video)
        self.Finish.setGeometry(QtCore.QRect(270, 80, 93, 28))
        self.Finish.setObjectName("Finish")
        self.Cancel = QtWidgets.QPushButton(Video)
        self.Cancel.setGeometry(QtCore.QRect(160, 80, 93, 28))
        self.Cancel.setObjectName("Cancel")

        self.B_SearchImage.clicked.connect(self.Search)

        self.retranslateUi(Video)
        QtCore.QMetaObject.connectSlotsByName(Video)

    def retranslateUi(self, Video):
        _translate = QtCore.QCoreApplication.translate
        Video.setWindowTitle(_translate("Video", "Video"))
        self.B_SearchImage.setText(_translate("Video", "⋮"))
        self.label_42.setText(_translate("Video", "VideoName"))
        self.label_34.setText(_translate("Video", "video:"))
        self.Finish.setText(_translate("Video", "Finish"))
        self.Cancel.setText(_translate("Video", "Cancel"))

    def Search(self):
        self.File = searching(VIDEOINDEX,self.Name)
        if (self.File != ""):
            self.label_42.setText(self.File.split("/")[-1])

    def clear(self):
        self.File = ""
        self.label_42.setText("VideoName")
        self.done = False

